name: Test

on:
  workflow_run:
    workflows: ["Train"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
    - name: Branch name
      run: echo "Running on branch ${GITHUB_REF##*/}"
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Pull the docker image
      run: docker pull adarun/cicd_assignment:${GITHUB_REF##*/}
    - name: Test model
      run: |
        OUTPUT=$(docker run adarun/cicd_assignment:${GITHUB_REF##*/})
        echo "Score:"
        echo "$OUTPUT"
        if [[ `echo "$OUTPUT 0.42" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi