name: TrainAndTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Branch name
      run: echo "Running on branch ${GITHUB_REF_NAME}"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag adarun/cicd_assignment:${GITHUB_REF_NAME}
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Push
      run: docker push adarun/cicd_assignment:${GITHUB_REF_NAME}
  test-model:
    needs: train-model
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Branch name
      run: echo "Running on branch ${GITHUB_REF_NAME}"
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Pull the docker image
      run: docker pull adarun/cicd_assignment:${GITHUB_REF_NAME}
    - name: Test model
      run: |
        OUTPUT=$(docker run adarun/cicd_assignment:${GITHUB_REF_NAME})
        echo "Score:"
        echo "$OUTPUT"
        if [[ `echo "$OUTPUT 0.42" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
